### ISSUE TITLE
Batch conversion of emails to PDFs

### ISSUE THREAD

**Issue by shaunplee** [ray-lothian/to-pdf#6]
It would be really great if this extension supported batch converting multiple emails to PDFs. One thought on the UI side would be to add the PDF buttons to the inbox and search views, so that a user can select emails by clicking the checkboxes for each of the emails to be converted. Clicking the PDF button would then convert all of the selected emails to PDF. Thanks!

**Comment by ray-lothian** [comment]
The extension now has a browser action button that does the batch conversion. Wait for the 0.2.4 release!

**Comment by shaunplee** [comment]
This worked perfectly. Thank you!
